name: Release

on:
  release:
    types: [published]

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-24.04
    needs: call-build-workflow
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download sanoid-portable artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.call-build-workflow.outputs.artifact_name }}

      - name: Assert Changelog updated for release version
        run: |
          version='${{ github.event.release.tag_name }}'
          version_heading="## $version"

          if ! grep -q "$version_heading" CHANGELOG.md; then
            echo "Error: CHANGELOG.md does not appear to contain release notes for \"$version\". A heading matching \"$version_heading\" was not found."
            exit 1
          fi

          echo "Ok: CHANGELOG.md contains release notes for \"$version\"."

      - name: Assert sanoid-portable version matches GitHub Release version
        run: |
          sudo apt install -y binfmt-support
          sudo update-binfmts --install APE /bin/sh --magic MZqFpD

          sudo chmod +x sanoid-portable

          sanoid_version=$(./sanoid-portable --version)
          release_version="${{ github.event.release.tag_name }}"

          echo "GitHub Release: $release_version"
          echo "sanoid-portable: $sanoid_version"

          if [ "$release_version" != "$sanoid_version" ]; then
            echo "Error: GitHub Release version \"$release_version\" does not match sanoid-portable version \"$sanoid_version\"."
            exit 1
          fi

          echo 'Ok: sanoid-portable version matches GitHub release version.'
          sha256sum sanoid-portable

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: sanoid-portable

      - name: Upload sanoid-portable to GitHub Release assets
        uses: softprops/action-gh-release@v2
        with:
          files: sanoid-portable
          tag_name: ${{ github.event.release.tag_name }}
          fail_on_unmatched_files: true
